from scope import Scope


class TypeChecker:
    def __init__(self, token_list):
        self.token_list = token_list  # takes the ast generated by the parser, runs through the parser
        self.global_scope = Scope()
        self.scope_stack = [self.global_scope]  # stack to manage scopes
        self.bracket_counter = []
        self.errors = []

    def check_types(self):
        """
        Entry point for type checking.
        """
        self._check_types_recursive(self.token_list, 0)
        if self.errors:
            for e in self.errors:
                print(e)
        return True

    def _check_types_recursive(self, tokens, start_index):
        """
        Recursively processes tokens, handling scopes and checking types.
        :param tokens: The list of tokens to process.
        :param start_index: The starting index for this scope.
        :return: The index after the current scope ends. --> for nested stack dive
        """

        current_scope = self.scope_stack[-1]  # Get the current scope
        index = start_index
        brackets = []
        inside_fstring_dbl = False
        inside_fstring_sgl = False
        while index < len(tokens):
            if self.errors:
                exit
            token = tokens[index]
            term, val = self.parse_token(token)

            """This logic checks for fstring to avoid accidental scope issues"""
            if 'f"' == val[:1]:  # viper only allows for "" fstrings
                inside_fstring_dbl = True  # not an optimal way to handle this but the odds of the first two chars of a random string being f" are very low
            if val == '"' and inside_fstring_dbl:
                inside_fstring_sgl = False
            if "f'" == val[:1]:  # viper only allows for "" fstrings
                inside_fstring_sgl = True  # not an optimal way to handle this but the odds of the first two chars of a random string being f" are very low
            if val == "'" and inside_fstring_sgl:
                inside_fstring_sgl = False

            """Parse brackets for scope"""
            # if term == "LBRACE" and not (inside_fstring_sgl or inside_fstring_dbl):
            #     # start consuming
            #     brackets.append(term)
            # we don't support fstrings yet
            """base case - RBRACE scope ended -> since we discount for fstring, the only {} that matter are the end of scope ones"""
            if term == "RBRACE":  # and not (inside_fstring_sgl or inside_fstring_dbl):
                # brackets.pop()
                return start_index

            """parse arguments here"""
            if term == "TYPE":  # Type def - func or var
                type_declared = val
                # skip ahead and fetch func or varname
                if index + 2 < len(tokens):
                    var_token = tokens[index + 2]
                    next_term, next_val = self.parse_token(var_token)
                    if next_term == "VAR":  # Check if it's followed by a variable
                        current_scope.define(next_val, type_declared)
                        index += 1  # Skip the variable token
                    elif next_term == "DEF":  # go parse the function
                        current_scope.define(next_val, type_declared)
                        new_scope = current_scope.clone()
                        new_scope.define_func_val(next_val, type_declared)
                        self.scope_stack.append(new_scope)
                        index = self._check_types_recursive(tokens, index + 1)
                        self.scope_stack.pop()  # delete the nested stack and move on
                        index += 1
                    else:
                        self.errors.append(
                            f"Type '{type_declared}' must be followed by a variable at index {index + 2}."
                        )
                        exit
            elif term == "VAR":  # Variable use
                var_type = current_scope.lookup(val)
                if var_type is None:
                    self.errors.append(f"Variable '{val}' used before declaration at index {index}.")
                    return
                index += 1
            # change scope
            elif term == "FUNC":
                # we are now using the function
                # TODO complete here
                new_scope = current_scope.clone()
                self.scope_stack.append(new_scope)
                index = self._check_types_recursive(tokens, index + 1)
                self.scope_stack.pop()  # delete the nested stack and move on
            # search legal operations
            elif val in ["for", "if", "elif", "else"]:
                # branch into new scope
                new_scope = current_scope.clone()
                self.scope_stack.append(new_scope)
                index = self._check_types_recursive(tokens, index + 1)
                self.scope_stack.pop()  # delete the nested stack and move on
            # search legal operations
            elif term == "OP":
                # use i now go backwards and collect previous and next arguments of the op --> should only be one
                # if each op works with two legal arguments it should be ok
                _, left_val = self.parse_token(tokens[index - 1])
                _, right_val = self.parse_token(tokens[index + 1])

                if current_scope.lookup(left_val) != current_scope.lookup(right_val):
                    self.errors.append(
                        f"Type mismatch between '{left_val}': {current_scope.lookup(left_val)} and '{right_val}': {current_scope.lookup(right_val)}. At index {index + 2}."
                    )
                index += 1

            elif val == "return":  # only handles returning variables with types for now
                _, right_val = self.parse_token(tokens[index + 1])
                if current_scope.lookup(right_val) != self.scope_stack[-2].function_return:
                    self.errors.append("Type mismatch in function return")
                index += 1
                return 
            else:
                index += 1
                continue

    def parse_token(self, token):
        parts = token.split(", ")
        return parts[0][1:], parts[1][:-1]


if __name__ == "__main__":

    examples2 = [
        {
            "code": """
                int :: x = 10; 
                NoneType :: def foo(int :: n):{
                    int :: x = 1;
                };
                int :: y = 1; 
                int :: x = 12;
                int :: a = x + y;
                """,
        }
    ]

    ex2 = [
        {
            """
            int :: def calculation1():{ 
                float :: num = 1.5; 
                return num;
            };
            """
        }
    ]

    tokens = [
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, x>",
        "<ASSIGN, =>",
        "<PYTHON_CODE, 10>",
        "<SEMICOLON, ;>",
        "<TYPE, NoneType>",
        "<TYPE_DEC, ::>",
        "<DEF, def>",
        "<FUNC, foo>",
        "<LPAREN, (>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, n>",
        "<RPAREN, )>",
        "<PYTHON_CODE, :>",
        "<LBRACE, {>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, x>",
        "<ASSIGN, =>",
        "<PYTHON_CODE, 1>",
        "<SEMICOLON, ;>",
        "<RBRACE, }>",
        "<SEMICOLON, ;>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, y>",
        "<ASSIGN, =>",
        "<PYTHON_CODE, 1>",
        "<SEMICOLON, ;>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, x>",
        "<ASSIGN, =>",
        "<PYTHON_CODE, 12>",
        "<SEMICOLON, ;>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, a>",
        "<ASSIGN, =>",
        "<VAR, x>",
        "<OP, +>",
        "<VAR, y>",
        "<SEMICOLON, ;>",
    ]

    t2 = [
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<DEF, def>",
        "<FUNC, print_one>",
        "<LPAREN, (>",
        "<RPAREN, )>",
        "<PYTHON_CODE, :>",
        "<LBRACE, {>",
        "<TYPE, int>",
        "<TYPE_DEC, ::>",
        "<VAR, num>",
        "<ASSIGN, =>",
        "<PYTHON_CODE, 1>",
        "<SEMICOLON, ;>",
        "<PYTHON_CODE, print>",
        "<LPAREN, (>",
        "<VAR, num>",
        "<RPAREN, )>",
        "<SEMICOLON, ;>",
        "<PYTHON_CODE, return>",
        "<VAR, num>",
        "<SEMICOLON, ;>",
        "<RBRACE, }>",
        "<SEMICOLON, ;>",
        "<FUNC, print_one>",
        "<LPAREN, (>",
        "<RPAREN, )>",
        "<SEMICOLON, ;>",
    ]

    typechecker = TypeChecker(t2)
    typechecker.check_types()
