class TypeChecker:
    def __init__(self, ast):
        self.ast = ast  # takes the ast generated by the parser, runs through the parser
        self.var_table = {}  # Maps variable names to their types
        self.func_table = {}  # Maps func names to their types
        self.errors = []

    def add_error(self, message, node=None):
        """Add an error message with optional node context."""
        self.errors.append(f"TypeError: {message}")

    def check(self):
        """Start type checking from the root of the AST."""
        if self.ast[0] == "Viper":
            self.visit_statement_list(self.ast[1])
        else:
            self.add_error("Root node must be 'Viper'.")
        return not self.errors

    def visit_statement_list(self, node):
        _, statements = node
        for statement in statements:
            self.visit_statement(statement)

    def visit_statement(self, node):
        if node[0] == "Statement":
            if isinstance(node[1], tuple) and node[1][0] == "TypeDeclaration":
                self.visit_var_declaration(node[1], node[2])

            elif isinstance(node[1], tuple) and node[1][0] == "ExpressionStatement":
                self.visit_expression_statement(node[1])

    def visit_var_declaration(self, type_dec, stmt_prime):
        _, type_token, _ = type_dec
        _, var_name_token, _, expr, _ = stmt_prime

        # extract the actual names and types
        var_type = type_token[1]
        var_name = var_name_token[1]


        # parse if the type declaration is legal --> adding correct type to typed var
        # due to how we parse python code, autocast numbers to strings, if the string is numerical we cast it to int type
        
        if var_name in self.symbol_table:
            self.add_error(f"Variable '{var_name}' is already declared.", type_dec)
        else:
            self.symbol_table[var_name] = var_type
            
        

    def visit_statement_prime(self, node):
        if node[0] == "StatementPrime":
            if len(node) > 2 and node[1][0] == "VAR" and node[2][0] == "ASSIGN":
                var_name = node[1][1]
                expr_type = self.visit_expression(node[3])
                if var_name in self.symbol_table:
                    var_type = self.symbol_table[var_name]
                    if var_type != expr_type:
                        self.add_error(
                            f"Type mismatch: variable '{var_name}' is of type '{var_type}' but assigned a value of type '{expr_type}'.",
                            node,
                        )
                else:
                    self.add_error(f"Variable '{var_name}' used before declaration.", node)

    def visit_expression_statement(self, node):
        if node[0] == "ExpressionStatement":
            self.visit_expression(node[1])

    def visit_expression(self, node):
        if node[0] == "Expression":
            simple_expr_type = self.visit_simple_expression(node[1])
            expr_prime_type = self.visit_expression_prime(node[2])
            return simple_expr_type or expr_prime_type

    def visit_simple_expression(self, node):
        if node[0] == "SimpleExpression":
            content = node[1]
            if isinstance(content, tuple):
                if content[0] == "PYTHON_CODE":
                    # Infer the type based on Python code, e.g., int literals
                    try:
                        eval_type = eval(content[1])
                        return type(eval_type).__name__
                    except Exception:
                        self.add_error(f"Could not infer type from PYTHON_CODE: {content[1]}.")
                        return None
                elif content[0] == "VAR":
                    var_name = content[1]
                    if var_name in self.symbol_table:
                        return self.symbol_table[var_name]
                    else:
                        self.add_error(f"Variable '{var_name}' used before declaration.")
                        return None
                elif content[0] == "TYPE":
                    return content[1]  # Return the type directly
                elif content[0] == "Loop":
                    self.visit_loop(content)
                    return None
                elif content[0] == "ParenthesizedExpression":
                    return self.visit_parenthesized_expression(content)
        return None

    def visit_expression_prime(self, node):
        if node[0] == "ExpressionPrime" and node[1]:
            return self.visit_simple_expression(node[1])
        return None

    def visit_loop(self, node):
        _, _, iterable_node, statement_list_node = node
        # Check the iterable
        iterable_type = self.visit_expression(iterable_node)
        if iterable_type != "list":
            self.add_error(f"Loop requires an iterable of type 'list', got '{iterable_type}'.")
        # Visit the body of the loop
        self.visit_statement_list(statement_list_node)

    def visit_parenthesized_expression(self, node):
        _, expr_node = node
        return self.visit_expression(expr_node)


# int :: x_a = 10;
# list :: y = range(0,x_a);
# for i in y:{
#     print(i);
# };

# Example Usage
ast = (
    "Viper",
    (
        "StatementList",
        [
            (
                "Statement",
                ("TypeDeclaration", ("TYPE", "int"), ("TYPE_DEC", "::")),
                (
                    "StatementPrime",
                    ("VAR", "x"),
                    ("ASSIGN", "="),
                    ("Expression", ("SimpleExpression", ("PYTHON_CODE", "10")), ("ExpressionPrime", None)),
                    ("SEMICOLON", ";"),
                ),
            ),
            (
                "Statement",
                ("TypeDeclaration", ("TYPE", "int"), ("TYPE_DEC", "::")),
                (
                    "StatementPrime",
                    ("VAR", "y"),
                    ("ASSIGN", "="),
                    ("Expression", ("SimpleExpression", ("PYTHON_CODE", "1")), ("ExpressionPrime", None)),
                    ("SEMICOLON", ";"),
                ),
            ),
            (
                "Statement",
                (
                    "ExpressionStatement",
                    (
                        "Expression",
                        ("SimpleExpression", "VAR", ("VAR", "x")),
                        (
                            "ExpressionPrime",
                            ("SimpleExpression", "OP", ("OP", "+")),
                            ("ExpressionPrime", ("SimpleExpression", "VAR", ("VAR", "y")), ("ExpressionPrime", None)),
                        ),
                    ),
                    ("SEMICOLON", ";"),
                ),
            ),
        ],
    ),
)


type_checker = TypeChecker(ast)
if type_checker.check():
    print("Type checking successful!")
else:
    for error in type_checker.errors:
        print(error)
